name: MacOS_Build

on:
  push:
    branches: [ master ]
    paths:
      - 'src/**'
      - 'build/common/**'
      - 'build/macos/**'
  pull_request:
    branches: [ master ]
    paths:
      - 'src/**'
      - 'build/common/**'
      - 'build/macos/**'
  workflow_dispatch:
    branches: [ master ]
    paths:
      - 'src/**'
      - 'build/common/**'
      - 'build/macos/**'

jobs:
  build:

    runs-on: macos-15-intel

    steps:
    - uses: actions/checkout@v3
    - name: make
      run: cd ./build/macos; make
